# Generated by Django 5.1.2 on 2024-10-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_password_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_reset_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_profile_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
